name: Run CI on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.0', '1.1', '1.2', '1.3', '1.4', '1.5', '1.6', '1.7', '1.8', '1.9', '1.10', '1.11']
        os: [ubuntu-latest, windows-latest, macos-13]
        exclude:
          - os: macos-13
            julia-version: 1.4
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/install-juliaup@v1
        with:
          julia-version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: ""
      - uses: julia-actions/julia-runtest@v1
        env:
          PYTHON: ""
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          files: ./lcov.info
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
